version: '3'

services:
  activity-detection:
    image: paulderfischer/computer-vision:linux-arm64-v8-latest
    volumes: 
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports: 
      - 5001:80
    devices:
      - /dev/video0:/dev/video0
    environment:
      # - "DISPLAY=$DISPLAY"
      - LS_HOST=backend:8080

  backend:
    image: paulderfischer/lightserver:arm
    ports:
      - 5002:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2