name: Docker Images CI/CD

on:
  push:
    branches: [ "main", "try-gh-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build Computer Vision
        uses: docker/build-push-action@v2
        with:
          context: ./ComputerVision
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            paulderfischer/computer-vision:latest
